name: ${project.name}
main: com.promcteam.fusion.Fusion
authors: [ Travja, goflish ]
version: ${project.version}
depend:
  - RiseCore
  - Codex
softdepend:
  - Sapphire
  - Divinity
api-version: 1.13
commands:
  craft: